const { SlashCommandBuilder } = require("discord.js");
const embedTemplate = require("../../utils/embedTemplate");
const protect = require("../../security/protect");

const STAR = "<a:starspin:1541482139759935558>";
const ARROW = "<:arrowright:1541479360932876398>";

module.exports = {
  data: new SlashCommandBuilder()
    .setName("regen")
    .setDescription("Send the regenerated link embed"),

  async execute(interaction) {
    if (!protect.applyRateLimit(interaction.user.id)) {
      return interaction.reply({ content: "Slow down.", flags: 64 });
    }

    const staffRoleId = "1350897509752373341";
    if (!interaction.member.roles.cache.has(staffRoleId)) {
      return interaction.reply({
        content: "You do not have permission to use this command.",
        flags: 64,
      });
    }

    await interaction.deferReply({ flags: 64 });

    const host = interaction.user;

    const messages = await interaction.channel.messages.fetch({ limit: 50 });
    const releaseMessage = messages.find((m) =>
      m.embeds[0]?.title?.includes("Session Release"),
    );

    const description = `> ${ARROW} The session link has been regenerated by ${host}.`;

    const { embed } = embedTemplate({
      title:
        `${STAR} Greenville Community - *__Link Regenerated__* ${STAR}`,
      description,
    });

    if (releaseMessage) {
      await releaseMessage.reply({ embeds: [embed] });
    } else {
      await interaction.channel.send({ embeds: [embed] });
    }

    await interaction.editReply({
      content: "Regenerated link embed sent successfully.",
    });
  },
};
